nav:
  Home: /
  Tags: /tags/
#  Writing: /posts/    #这里是指博客服务器地址
  Archives: /Archives/ #这里是指本地静态文件
  Projects: http://github.com/caitb
  Search: /Search/

projects_url: http://github.com/caitb

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/caitb
        facebook: /
        linkedin: /
    show_all_posts: true
    post_count: 10
    highlight: tomorrow-night-blue

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-37473492-6 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
